### PR TITLE
Fix munchkin api issue #6

### PR DESCRIPTION
**Pull request by mccrodp**
Main PR for https://github.com/mccrodp/marketo_rest/issues/6. I've a few more remaining items before I can merge this, namely:
- Set fields to be enabled by default
- Add test code for field-definition retrieval UI to _configure.feature_
- Add webform submodule integration

@neclimdul - I won't tag you on the sub issues, you're probably getting loads of notifications. I'll just merge them, visible here from the sub-PRs.

### CODE REVIEW

**Comment by mccrodp** [comment]
Only one item remaining now, to "Add webform submodule integration".

**Comment by mccrodp** [comment]
Hey @neclimdul - I believe this is ready for review now. I'm sure there are some issues remaining, but I will be working with this now on my client project and will fix as I / you or others find anything. 

The last part was a bit tricky to try to change as little as possible of what was already there, but also map the `key|value` fields depending on API used.

If you could take a look at this that would be great, thank you!

**Comment by neclimdul** [comment]
Well shoot, I pulled down too early to review this morning. It was looking good but I'll take another look! Thanks!

**Comment by neclimdul** [comment]
It looks like the marketo_id isn't being saved on the individual webform management page so its always 0?

**Comment by mccrodp** [comment]
Thank you! That should be better now. The options array was using `array_merge` and was losing the `marketo_id` so was using a incorrect value. I need to add alphabetic sorting back to `_marketo_rest_get_field_options` next.

It would have been nice to add a test on that UI also, but I didn't get time.

**Comment by neclimdul** [comment]
Yeah that was actually the same change. It seems to make things better _before_ going into form api but something in the form API seems to be trashing it still. For the field I'm testing the value is being saved as 1 instead of 0 but the id is suppose to be 4.

**Comment by mccrodp** [comment]
Hey, could you attach a screengrab of what you mean? I'm not 100% sure of which interface now / what is going wrong. I'm sure it's pretty close, probably just something minor that needs an update since restructuring. Thanks.

**Comment by neclimdul** [comment]
The problem was that I'd already saved the form and the value was undefined. There is another array_merge right below that clobbers it again. PR should be sitting in your inbox.

**Comment by neclimdul** [comment]
So technically, there's a bug in munchkin.js I have to work around to get tracking code and submissions working but that's not specific to this issue so I'll open another issue/PR. This fixes webforms for me and their populating fields in marketo now. Thanks!

:shipit:

**Comment by mccrodp** [comment]
Ok, yes, a separate issue/PR sounds great. I'll merge this one tomorrow when I resolve the branch conflicts. Appreciate the testing and PRs so far, really helpful.

**Pull request merged**
